### ISSUE TITLE
training dataset

### ISSUE THREAD

**Issue by huyz1117** [Eustaceyi/11785-Project-CartoonFaceGAN#3]
Hi! Thank you for sharing the project! I have a problem. What is the training dataset of the Project?

**Comment by Eustaceyi** [comment]
Human faces are from [https://github.com/NVlabs/ffhq-dataset](https://github.com/NVlabs/ffhq-dataset) used in NVIDIA StyleGAN paper. And cartoon faces are from [Cartoon Set](https://google.github.io/cartoonset/).
